### ISSUE TITLE
Trying to download a file with FTP

### ISSUE THREAD

**Issue by mr** [GaloisInc/curl#15]
I'm trying to download a file over FTP, but for some reason my files come out smaller than they should be. It's always a fair amount less, but it varies slightly from run to run. I think this is about as straightforward as you can be. For reference it works fine with this C example from the libcurl website: https://curl.haxx.se/libcurl/c/ftpget.html

My curl version is 7.47.1.

Here's the code I'm using:

```
import qualified Network.Curl as C
import System.IO

main :: IO ()
main = do
    let url = "ftp://user:pass@host.net/file"
        dest = "/home/matt/file"
    C.withCurlDo $ withFile dest AppendMode $ \h -> do
        c <- C.initialize
        C.setopts c
            [ C.CurlURL url
            , C.CurlWriteFunction $ C.callbackWriter $ hPutStr h
            , C.CurlVerbose True
            ]
        res <- C.perform c
        print res
```

Any idea what might be wrong?

**Comment by yav** [comment]
Hello,
unfortunately, this library doesn't have an active maintainer at the moment, so I am not sure what is wrong.  The binding was written quite a long time ago, and it is possible that something changed in `curl` that requires updates to the binding, or it is just a bug.

Overall, I'd say that if you just want to download some files there are probably better alternatives on `hackage`.   If, OTOH, you are interested in doing some hacking on the library, please dive in---this library could really use some love.

**Comment by mr** [comment]
Thanks for the response! I've been trying to do secure FTP for awhile and this seemed like the best solution. I'll probably take a look to see what's wrong some time in the future.
