### ISSUE TITLE
GSSNegotiate fails.

### ISSUE THREAD

**Issue by Magicloud** [GaloisInc/curl#7]
An internal website that requires auth. I could do `curl --negotiate -v -u : -k 'https://www.company.com/'`.

But with Network.Curl, I got:

```
...
< HTTP/1.1 401 Authorization Required
< Date: Wed, 08 Jan 2014 07:49:02 GMT
< Server: Server
* gss_init_sec_context() failed: : Success< WWW-Authenticate: Negotiate
< WWW-Authenticate: Basic realm="Domain (Windows) Login"
< Content-Type: text/html; charset=iso-8859-1
* no chunk, no close, no size. Assume close to signal end
<
* Closing connection #0
```

**Comment by joozek78** [comment]
@Magicloud I know it was over a year ago, but I have similar problem (failed: Success) and solution is nowhere to be found. Maybe you remember what was the root cause / solution to this?

**Comment by Magicloud** [comment]
Hi, @joozek78 . The reason was that I used wrong parameters. `CurlUserPwd ":"` should be used.
But of course, you need to confirm everything should work with curl command. Then use the exactly same parameters in Haskell.

**Comment by joozek78** [comment]
Thanks for help! Unfortunately I figured out my problem is with git using curl, not curl itself :( Back to debugging git
